### ISSUE TITLE
SOLVED: Setting self.clipsToBounds = true causes issues

### ISSUE THREAD

**Issue by hrushka** [SwipeCellKit/SwipeCellKit#107]
I was experiencing some issues with the actions not displaying the first time the cell was swiped open. After it reset fully, the actions would display.

I tracked it down to the fact that instead of clipping the elements in my cell individually, I was using self.clipsToBounds = true. This was causing the issue. After removing it and setting it on the content view, it fixed the issue.

Not sure if you want to do anything with this, just thought you should know in case anyone else came across this issue.

**Comment by kurabi** [comment]
What version are you using?

**Comment by hrushka** [comment]
2.0.0

**Comment by kurabi** [comment]
Are you overriding the prepareForReuse method and not calling super?

Because `SwipeTableViewcell` calls the `reset()` method when `prepareForResuse()` is invoked and it sets `clipsToBounds = false`.

See: https://github.com/SwipeCellKit/SwipeCellKit/blob/11d86e3864329a970925d985f5273d76b5d74afc/Source/SwipeTableViewCell.swift#L84

**Comment by hrushka** [comment]
I'm using a setup method on the cell when it's dequeued in the cellForItem:atIndex delegate call. In that setup call, once it has the data needed to render it makes a decision if it needs to clip or not. So when clipsToBounds=true was being called, prepareForReuse() would have already been run.

**Comment by kurabi** [comment]
Just to be clear, you are not overriding the prepareForResuse method?

**Comment by hrushka** [comment]
That’s correct. I am not.
