### ISSUE TITLE
Crash on Delete

### ISSUE THREAD

**Issue by grifas** [SwipeCellKit/SwipeCellKit#192]
In my project, I'm getting a crash when I try to delete an item. So I tried with your example with my configuration which is having number of section equals to emails.count and just one row in each section corresponding to the item. Of course I changed indexPath.row by indexPath.section in the right place.

It is possible to delete a row in a section and if it's the last row, delete in the same time the section ?

**Comment by Mijail** [comment]
It crashes because the action fulfill calls `                self.delegate?.swipeController(self, didDeleteSwipeableAt: indexPath)
`
and that delegate does this:
`        tableView?.deleteRows(at: [indexPath], with: .none)
`
And it doesn't delete the section if it is the last row of it, so yes there should be a check if the element is the last one of the section.

**Comment by Mijail** [comment]
I can't do it right now, but I think this issue should be open. I will work on it when I can.

**Comment by Mijail** [comment]
If I recall the example only has 1 section, the way to test it is having more than one. (numberOfSections(in tableView: UITableView) )

**Comment by kurabi** [comment]
@Mijail I tried that. Didn't work either.

**Comment by weakfl** [comment]
I've got the same issue:
- collectionview with 2 sections
- deleting last item in section 0 -> crashes in `SwipeCollectionViewCell.swift`, line 238:

```swift
    func swipeController(_ controller: SwipeController, didDeleteSwipeableAt indexPath: IndexPath) {
        collectionView?.deleteItems(at: [indexPath])
    }
```

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: key cannot be nil'`

**Comment by kurabi** [comment]
@weakfl Thats not your issue.

**Comment by weakfl** [comment]
@kurabi Does it matter?

FWIW, it's an iOS bug anyway. I was able to work around the issue by using `fulfill(with: .reset)` and using `collectionView.reloadData()` instead of `collectionView.performBatchUpdates` if I'm dealing with the last item in the section...

**Comment by weakfl** [comment]
I didn't really like the `collectionView.reloadData()` solution because of the missing animation, so I've debugged this a little further.

It turns out the crash is triggered by returning `CGSize.zero` for a supplementary view during deletion. Returning `CGSize(width: collectionView.bounds.size.width, height: CGFloat.leastNonzeroMagnitude)` is  a better workaround for the issue, as it will allow to run `performBatchUpdates` without problems.

@kurabi So it's definetely not an issue of SwipeCellKit (which is is a wonderful library btw).

**Comment by APvanGrootel** [comment]
Hi. I think the crash happens when didDeleteSwipeableAt is calling deleteRows when there is only one row inside a section. When this is the case, it should call deleteSections

**Comment by dbogatz** [comment]
@weakfl thanks for support. But where should I add CGSize(width: collectionView.bounds.size.width, height: CGFloat.leastNonzeroMagnitude)?
Wouldn't it better if the library adds a check for last row?

**Comment by weakfl** [comment]
@dbogatz 

> But where should I add CGSize(width: collectionView.bounds.size.width, height: CGFloat.leastNonzeroMagnitude)?

Depends on your layout. If you're using `UICollectionViewFlowLayout` for example, you'll have to return this as `referenceSizeForHeaderInSection`.

> Wouldn't it better if the library adds a check for last row?

That's debatable ;) See @APvanGrootel's comment.
