### ISSUE TITLE
Upgrade to Swift 5

### ISSUE THREAD

**Issue by jlaws** [SwipeCellKit/SwipeCellKit#302]
## Expected Results

No warning to convert SwipeCellKit.framework to Swift 5

## Actual Results

Xcode created warnings to convert SwipeCellKit.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by thoughtcastdavid** [comment]
![image](https://user-images.githubusercontent.com/42627029/55731926-e36a2f00-59cf-11e9-9957-36b2ad40f8bf.png)


im getting this error...

**Comment by kurabi** [comment]
Ignoring the warning on by telling Xcode not to remind you is an acceptable solution. The `develop` branch of SwipeCellKit version uses Swift 5 as its version.

**Comment by jlaws** [comment]
Thanks, works great

**Comment by BetilloGG** [comment]
Hi, i have this error
it does not allow me to compile unless I added a nil as an alternative.

![Captura de Pantalla 2019-04-17 a la(s) 12 20 57](https://user-images.githubusercontent.com/43450363/56307847-719a8f80-610b-11e9-8c64-1302e7d020fe.png)


It could affect? but I do not like it because every time I install the pods I have to do this.
