### ISSUE TITLE
Change actions view height

### ISSUE THREAD

**Issue by andrey-lisovskiy** [SwipeCellKit/SwipeCellKit#330]
In my project I've made additional contentView for cell, which is smaller than cell height, to imitate padding between cells. But it looks strange. How can I change actions view height?

<img width="187" alt="Снимок экрана 2019-08-02 в 12 44 58" src="https://user-images.githubusercontent.com/7079771/62361360-8ae11380-b523-11e9-83c4-7429c30086dd.png">

**Comment by kurabi** [comment]
The height of the actions views is the same as the cell. I suggest you switch to a collection view to create the gap between the cells correctly or use a circular button style.

**Comment by ytpm** [comment]
Is it possible to add padding to the actions views instead of using UICollectionView? I want to achieve this also and can't figure out how to change it. Maybe adding padding to the top and bottom of the actions views will allow adding space between the cell and the actions views? If so, where is it located?
