### ISSUE TITLE
UICollectionViewCell

### ISSUE THREAD

**Issue by fabb** [SwipeCellKit/SwipeCellKit#4]
Nice library when wanting more than possible with `tableView(_:editActionsForRowAt:)`. Would it be possible to adopt this in order to work with `UICollectionViewCell`?

**Comment by jerkoch** [comment]
Thanks @fabb - Yes, absolutely!  That's why I named it generically as `SwipeCellKit`.  I'm not much of an expert with `UICollectionView`, so I'd love some help!

**Comment by fabb** [comment]
Right now a bit stressful, but if we'll do our planned refactoring in a few months to completely move from UITableView to UICollectionView, I'll point the one from our team doing it to this library.

**Comment by jerkoch** [comment]
👍

**Comment by mschonvogel** [comment]
Proof of concept for UICollectionView: https://github.com/mschonvogel/SwipeCellKit

**Comment by mschonvogel** [comment]
You're welcome! It was actually pretty straight forward. I'm curious about your ideas on how to make this library universally work for both, UICollectionView and UITableView. ✌️

**Comment by jerkoch** [comment]
Hey @mschonvogel - I was about to ask you the same question! 🤣 Having a working version for both will definitely help clarify how to decouple the generic components from each view specific implementation.   It has also started to become clearer as I've refactored things while introducing other new features.

**Comment by MarvinNazari** [comment]
Hey @jerkoch  and @mschonvogel maybe we could do something like [this](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/Source/ViewFactory.swift)?
but much simpler.

**Comment by jerkoch** [comment]
Hey @MarvinNazari - Thanks for sharing! 👍 I'm a big fan of @jessesquires work!

**Comment by ericreid** [comment]
I'm using the fork put together by @mschonvogel. It would be great if we could get that merged into the main project. I'd be happy to help if I can.

Nice work by everyone!

**Comment by fishcharlie** [comment]
@ericreid How were you able to implement it? @mschonvogel's fork doesn't have any updates to the documentation to discuss UICollectionViewCell looks like.

**Comment by D-Link13** [comment]
Can anyone explain how to make this work for CollectionView?

**Comment by musbaalbaki** [comment]
Any update on this please?

**Comment by magonicolas** [comment]
Has this been updated? I Really need to use it whit a collection view.

**Comment by musbaalbaki** [comment]
Same here

**Comment by D-Link13** [comment]
For everyone who want to use it with a collectionView, just use [mschonvogel's brunch](https://github.com/mschonvogel/SwipeCellKit) in your pod file, like so:
`pod 'SwipeCellKit', :git => 'https://github.com/mschonvogel/SwipeCellKit.git'`

**Comment by godexsoft** [comment]
It's more than a year later and you still didn't make UICollection support.. pure sadness. And no, we don't want to use a branch that is 66 commits with bug fixes behind the original. Please take the few hours you need for this to implement it. Such an awesome library and no collection view support. Does anyone even use UITableView still in 2018?

**Comment by fabb** [comment]
@godexsoft this is open source. People work in their free time to provide things that help other people without charge.

**Comment by fishcharlie** [comment]
@fabb That is fine, but when there is an open PR (#142) that @kurabi said he would review over the next few days back on January 25th, with no updates since that is not open source. That is just not taking the time to maintain a project that you created. It's totally fine to work on things in your free time, and I get that is open source, but you always need someone to maintain it and put a decent amount of effort into it. Considering there is an open PR for this that @kurabi isn't addressing, @godexsoft is PERFECTLY in the right to be sad and frustrated about this.

This is a major feature request,  I mean this was issue/pr number 4. So it's obviously a highly requested feature. The maintainers and owners of this project need to layout guidelines and be clear about what needs to happen to that PR to get merged in and get this done. Obviously the community is willing to help build it to make it reality because there is already a PR for it...

**Comment by kurabi** [comment]
Thank you all for your input.

The `UICollectionView` support in that PR is a good initial start, however it still needs a good amount of work due to the amount of duplicated code, and other non-trivial collection view nuances that are different that `UITableView`, so it not as simple as "Please take the few hours you need for this to implement it." I will note on the PR on what is needed to get it accepted.

The project is actively maintained. Just because this particular feature isn't being worked on it doesn't mean this project isn't being maintained.

**Comment by fishcharlie** [comment]
@kurabi Thank you very much. I know speaking for myself and I believe for many others we really appreciate your work on this code. If I get some time I'll try to look at your comments on that PR and maybe I'll get around to helping out at some point.

**Comment by godexsoft** [comment]
Glad to see i triggered a bit of a shitstorm here :) maybe things will get done finally.
I cloned the repo to see how much work it would be to implement it properly and yea i can see it's not that simple - no one wants to blindly copy and paste files and duplicate the logic. I'm sure it would take less time for Jeremy or whoever wrote the original code to do it than for me to figure it out tho. 
I just don't want to end up making a whole new library for the same reasons Jeremy started this one - absence of a good working solution. And I'm still confused how is this not top priority from the very beginning of the project to have both table view and much more importantly collection view supported? Hope we can make it work. I will try to help too. Thanks for your time

**Comment by kurabi** [comment]
This feature is now complete and has been merged onto master. #188.

Thank you for all the contributed to this. Thank you to @kreeger @gcox and @mschonvogel.
