### ISSUE TITLE
Crash on iOS 10.0

### ISSUE THREAD

**Issue by reden87** [SwipeCellKit/SwipeCellKit#51]
**Hey guys,**

I tested my app on an iPhone 5s which is running iOS 10.0 and sadly SwipeCellKit crashes the app when I try to swipe my cells.

Tried the sample app and it crashes too. Not sure if you can reproduce it on Simulator since I'm unable to download 10.0 simulator at the moment.. :(

Here the exact line where the sample app crashes:
<img width="882" alt="screen shot 2017-06-09 at 14 54 13" src="https://user-images.githubusercontent.com/869119/26976349-b738ab4c-4d23-11e7-81a3-a550b0f96ad2.png">

I'm not sure what's the reason of the crash yet (maybe UIImpactFeedbackGenerator is buggy on iOS 10.0??), do you have any idea or quick solution?

**Comment by reden87** [comment]
No crash on iPhone 6s running 10.0.2

**Comment by kurabi** [comment]
@reden87 This seems like a bug in iOS 10.0.0 where `UIImpactFeedbackGenerator` crashes for non-haptic supported devices. Any suggestions on how we can fix this without listing out all the non-supported devices?

**Comment by kurabi** [comment]
I made availability check excluded 10.0.0 devices since there is no other way to determine if the device supports haptic feedback, and since this issue is specifically for 10.0.0 devices as corroprated by you and this post:
https://stackoverflow.com/questions/40270596/uifeedbackgenerator-object-creation-crashes-on-ios-10-0

**Comment by reden87** [comment]
@kurabi could you bump the CocoaPod version to 1.9.1 too?
