### ISSUE TITLE
Any plan iOS 8 supported?

### ISSUE THREAD

**Issue by aloveric** [SwipeCellKit/SwipeCellKit#62]
It is a very nice cell action, do you have any to support iOS 8?

**Comment by dzzh** [comment]
I second here. I saw the author's comment in one of previous issues that he doesn't want to support iOS 8 due to low user count. While I agree that the number of users with iOS 8 is low, some of the applications still have to support it for different reasons. Without iOS 8 support it's not only this small fraction of users will not be able to use the framework, but also the app developers that have to support iOS 8.

It seems that it's very easy to make the framework work with iOS 8. I'll prepare a patch.

**Comment by aloveric** [comment]
Thanks for your commit @dzzh . 
Yes, there is only small group of iOS 8 devices. However, most of apps are still support it to extend its users.

**Comment by aloveric** [comment]
@dzzh It works fine~~~

**Comment by kurabi** [comment]
@dzzh Thanks for the pull request. Will review to make sure iOS 9 and 10 are not impacted and possibly merge. Once UICollectionView support is added as that is more important and don't want iOS 8 incompatibilities to affect that.
